import type { FeedGroup } from '../app/types/feed'
import { myFeed } from '../blog.config'

export default [
	{
		name: 'WUSTACM',
		desc: '武汉科技大学 ACM 俱乐部相关站点。',
		entries: [
			myFeed,
			{
				author: 'WUSTACM',
				sitenick: 'GitHub',
				title: 'WUSTACM GitHub Organization',
				desc: '武汉科技大学 ACM 俱乐部的 GitHub 组织主页。',
				link: 'https://github.com/WUSTACM',
				icon: '/assets/wustacm-logo.png',
				avatar: '/assets/wustacm-logo.png',
				archs: ['GitHub Pages'],
				date: '2025-06-15',
				comment: '代码仓库、文档和博客项目集中维护处。',
			},
		],
	},
	{
		name: 'WUSTer们',
		desc: 'WUSTer 个人站点与文档。',
		entries: [
			{
				author: 'Jianges',
				sitenick: '姜一',
				title: '杂话铺',
				desc: '留此一方素纸，待岁生苔。',
				link: 'https://blog.jianges.com/',
				feed: 'https://blog.jianges.com/atom.xml',
				icon: 'https://blog.jianges.com/favicon.png',
				avatar: 'https://jianges.com/wp-content/uploads/2025/12/1765434218-jianges.jpg',
				archs: ['Nuxt', 'Vercel'],
				date: '2026-07-05',
			},
			{
				author: 'everlasting',
				sitenick: 'aMore',
				title: 'everlasting 的博客',
				desc: 'aMore 的个人博客。',
				link: 'https://everlastingblog.top/',
				feed: 'https://everlastingblog.top/rss.xml',
				icon: 'https://everlastingblog.top/favicon-32x32.png',
				avatar: 'https://jianges.com/wp-content/uploads/2026/01/1767861756-avatar.jpg',
				archs: ['Astro'],
				date: '2026-07-05',
			},
			{
				author: 'scandi dreams',
				sitenick: 'scandi',
				title: 'scandi-blog',
				desc: 'scandi 的个人博客。',
				link: 'https://blog.scandidreams.top/',
				icon: 'https://blog.scandidreams.top/favicon.ico',
				avatar: 'https://jianges.com/wp-content/uploads/2026/01/1767865673-%E5%A4%B4%E5%83%8F.png',
				archs: ['Hexo'],
				date: '2026-07-05',
			},
			{
				author: 'Icho',
				title: 'Icho 的个人博客',
				desc: 'Icho 的个人博客。',
				link: 'https://ichooooooo.github.io/',
				icon: 'https://ichooooooo.github.io/img/favicon.jpg',
				avatar: 'https://jianges.com/wp-content/uploads/2026/01/1768288592-avatar.jpg',
				archs: ['Hexo', 'GitHub Pages'],
				date: '2026-07-05',
			},
			{
				author: 'shoper',
				sitenick: 'docs',
				title: 'shoper docs',
				desc: 'shoper 的文档站。',
				link: 'https://docs.scandidreams.top/',
				feed: 'https://docs.scandidreams.top/feed_rss_created.xml',
				icon: 'https://docs.scandidreams.top/assets/2026-3-20-1.jpg',
				avatar: 'https://image.wustacm.com/i/2026/02/17/si2wc7.png',
				archs: ['Material for MkDocs'],
				date: '2026-07-05',
			},
			{
				author: 'Chord',
				sitenick: 'Songline',
				title: 'Songline 的博客',
				desc: '个人博客，分享技术，还会提供些神秘小工具 wow',
				link: 'https://blog.songline-blog.com/',
				feed: 'https://blog.songline-blog.com/index.xml',
				avatar: 'https://blog.songline-blog.com/uploads/admin/snowMan.png',
				icon: 'https://blog.songline-blog.com/uploads/admin/main_logo.png',
				archs: ['Hugo'],
				date: '2026-08-27',
			},
		],
	},
] satisfies FeedGroup[]
